---
- name: Ensure the Operator ArgoCD Application is present
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: '{{ operators_iac_repo["name"] }}'
        namespace: '{{ operators_iac_repo["namespace"] }}'
      spec:
        project: default
        source:
          repoURL: '{{ operators_iac_repo["url"] }}'
          targetRevision: HEAD
          path: '{{ operators_iac_repo["path"] }}'
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

- name: Wait for Operator ArgoCD Application to exist
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: '{{ operators_iac_repo["name"] }}'
    namespace: '{{ operators_iac_repo["namespace"] }}'
  register: argocd_operator_object
  retries: 30
  delay: 10
  until: argocd_operator_object.resources | length > 0

- name: Wait until Operator ArgoCD Application status.health.status is 'Healthy'
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: '{{ operators_iac_repo["name"] }}'
    namespace: '{{ operators_iac_repo["namespace"] }}'
  register: argocd_operator_status
  retries: 30
  delay: 10
  until: 
    - argocd_operator_status.resources[0].status.health.status is defined
    - argocd_operator_status.resources[0].status.health.status == 'Healthy'
...
